# Generated by Django 5.0.3 on 2024-03-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaddress',
            name='email',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
